# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-23 11:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customername',
            name='contract_number',
            field=models.CharField(blank=True, max_length=251, null=True),
        ),
    ]
