# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-23 11:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_customername_contract_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='customername',
            name='cse_name',
            field=models.CharField(blank=True, max_length=251, null=True),
        ),
        migrations.AddField(
            model_name='customername',
            name='location',
            field=models.CharField(blank=True, max_length=251, null=True),
        ),
        migrations.AddField(
            model_name='customername',
            name='pms',
            field=models.CharField(blank=True, max_length=251, null=True),
        ),
        migrations.AddField(
            model_name='customername',
            name='renewed_amount',
            field=models.CharField(blank=True, max_length=251, null=True),
        ),
    ]
