# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-23 12:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_auto_20181023_1159'),
    ]

    operations = [
        migrations.AddField(
            model_name='customername',
            name='tax',
            field=models.CharField(blank=True, max_length=251, null=True),
        ),
    ]
