# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-24 12:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_customername_tax'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customername',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
